// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// adj2list
std::vector<std::vector<double> > adj2list(SEXP X_);
RcppExport SEXP rdssim_adj2list(SEXP X_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    __result = Rcpp::wrap(adj2list(X_));
    return __result;
END_RCPP
}
// rdssim_cpp
Rcpp::NumericMatrix rdssim_cpp(Rcpp::List rcpp_adjlist, std::string rType, bool Markovian, int nSamples, int nReferrals, int seedNode, int rseed);
RcppExport SEXP rdssim_rdssim_cpp(SEXP rcpp_adjlistSEXP, SEXP rTypeSEXP, SEXP MarkovianSEXP, SEXP nSamplesSEXP, SEXP nReferralsSEXP, SEXP seedNodeSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type rcpp_adjlist(rcpp_adjlistSEXP);
    Rcpp::traits::input_parameter< std::string >::type rType(rTypeSEXP);
    Rcpp::traits::input_parameter< bool >::type Markovian(MarkovianSEXP);
    Rcpp::traits::input_parameter< int >::type nSamples(nSamplesSEXP);
    Rcpp::traits::input_parameter< int >::type nReferrals(nReferralsSEXP);
    Rcpp::traits::input_parameter< int >::type seedNode(seedNodeSEXP);
    Rcpp::traits::input_parameter< int >::type rseed(rseedSEXP);
    __result = Rcpp::wrap(rdssim_cpp(rcpp_adjlist, rType, Markovian, nSamples, nReferrals, seedNode, rseed));
    return __result;
END_RCPP
}
