# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adj2list <- function(X_) {
    .Call('rdssim_adj2list', PACKAGE = 'rdssim', X_)
}

rdssimMarkov <- function(rcpp_adjlist, rType, nSamples, nReferrals = 1L, seedNode = 1L, rseed = 1L) {
    .Call('rdssim_rdssimMarkov', PACKAGE = 'rdssim', rcpp_adjlist, rType, nSamples, nReferrals, seedNode, rseed)
}

