# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert adjacency matrix to adjacency list 
#'
#'@param X adjacency matrix
#'
#'@export
#'
adj2list <- function(X) {
    .Call('rdssim_adj2list', PACKAGE = 'rdssim', X)
}

#' Respondent-driven sampling simulator
#'
#'@param rcpp_adjlist adjacancy list. Refert to \code{\link{adj2list}}
#'@param rType referral type
#'@param nSamples numeber of sample to be collected
#'@param nReferrals number of referrals per person
#'@param seedNode starting seed node (person)
#'@param rseed random seed for the random number generator that generates the random referrals
#'
#'@export
#'
rdssimMarkov <- function(rcpp_adjlist, rType, nSamples, nReferrals = 1L, seedNode = 1L, rseed = 1L) {
    .Call('rdssim_rdssimMarkov', PACKAGE = 'rdssim', rcpp_adjlist, rType, nSamples, nReferrals, seedNode, rseed)
}

