# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adj2list <- function(X_, acType) {
    .Call('rdssim_adj2list', PACKAGE = 'rdssim', X_, acType)
}

rdssim_cpp <- function(rcpp_adjList, rcpp_acAdjList, referralType, wReplacement, nSamples, nReferrals, seedNode, rseed) {
    .Call('rdssim_rdssim_cpp', PACKAGE = 'rdssim', rcpp_adjList, rcpp_acAdjList, referralType, wReplacement, nSamples, nReferrals, seedNode, rseed)
}

